spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Contatos
    username: postgres
    password: 123qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
